server:
  port: 8080

spring:
  datasource:
    username: root
    password: asuzncmi666
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      jdbc:
      batch_size: 50
      order_inserts: true
      order_updates: true
    show-sql: false
  sql:
    init:
      mode: always


indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.ipfran.ru
      name: IP Fran
